---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 了解NetApp Workload Factory 中工作負載的最新變化。 
---
= NetApp Workload Factory 的最新變化
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解NetApp Workload Factory 中工作負載的最新變化。



== 2026年1月4日



=== 資料庫工作負載



==== 問我關於人工智慧助理首頁整合的問題

Workload Factory 控制台主頁嵌入了 Ask me AI 助手，讓您可以詢問有關您自己的儲存環境的問題，直接從您的環境中獲取個人化見解，並參考先前的對話。您可以與「問我」進行交互，以了解您的工作負載、解決問題並了解更多關於工作負載工廠的資訊——所有這些都無需離開控制台。



=== VMware 工作負載



==== 問我關於人工智慧助理首頁整合的問題

Workload Factory 控制台主頁嵌入了 Ask me AI 助手，讓您可以詢問有關您自己的儲存環境的問題，直接從您的環境中獲取個人化見解，並參考先前的對話。您可以與「問我」進行交互，以了解您的工作負載、解決問題並了解更多關於工作負載工廠的資訊——所有這些都無需離開控制台。



== 2025年12月18日



=== 資料庫工作負載



==== Active Directory 整合增強功能

使用「進階建立」選項部署 Microsoft SQL Server 時，資料庫工作負載工廠將包含三個新的 Active Directory (AD) 欄位。這些增強功能可讓您指定 Active Directory 加入首選項並使用託管服務帳戶。

新增的 AD 欄位包括：

* 首選網域控制器
* 首選組織單元路徑
* 目標 Active Directory 群組


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["部署 Microsoft SQL Server"]



== 2025年12月4日



=== Amazon FSX for NetApp ONTAP 產品



==== 支援用於ONTAP的 FSx 的 AWS S3 存取點

NetApp Workload Factory為您的 FSx for ONTAP檔案系統提供 AWS S3 存取點。您可以使用 S3 存取點建立磁碟區，將 S3 存取點指派給現有捲，並從 Workload Factory 控制台管理 S3 存取點。使用 S3 存取點，您可以透過 AWS S3 API 存取駐留在 SMB/CIFS 或 NFS 磁碟區上的檔案資料。這樣，您就可以將現有資料與支援 S3 存取點的 AWS 服務的 GenAI、ML 和分析功能整合在一起。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["使用 S3 存取點建立磁碟區"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["管理磁碟區的 S3 存取點"]




== 2025年11月27日



=== Amazon FSX for NetApp ONTAP 產品



==== NetApp Workload Factory中的區塊設備支持

NetApp Workload Factory中新引入的區塊裝置支持，可更有效地管理您的區塊裝置。此功能可讓您查看 iSCSI LUN 的詳細資訊並增加其容量，從而為您的儲存需求提供更大的靈活性。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["在工作負載工廠中管理區塊設備"]



==== 精心設計的分析更新

Workload Factory 會分析您的 FSx for ONTAP檔案系統，以識別下列設定：

* 刪除不必要的快照：檢查磁碟區中是否存在過時且不必要的快照，這些快照可以刪除以降低成本。
* FlexGroup容量重新平衡：檢查FlexGroup容量是否在其成員容量之間保持均衡，以確保最佳效能。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["查看 FSx for ONTAP檔案系統的良好架構狀態"]



==== NetApp Workload Factory中的 EMS 事件 AI 分析器

NetApp Workload Factory推出了一款基於 AI 的ONTAP事件管理系統 (EMS) 事件分析器。此功能透過分析 EMS 事件數據，提供見解和建議，幫助您快速識別和解決問題。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["在工作負載工廠中分析 EMS 事件"]



==== 監控 FSx for ONTAP檔案系統的成本和使用趨勢

您可以直接從NetApp Workload Factory控制台監控 FSx for ONTAP檔案系統的成本和使用趨勢。此功能提供儲存消耗和成本指標以及詳細成本，幫助您優化資源分配和預算規劃。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["在 Workload Factory 中追蹤 FSx for ONTAP檔案系統的成本"]



==== 在NetApp Workload Factory中管理檔案系統的 FSx 標籤

直接從NetApp Workload Factory控制台輕鬆管理檔案系統的 FSx 標籤。此功能可讓您新增、編輯或刪除標籤，從而更好地組織和分類您的 FSx for ONTAP檔案系統。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["在工作負載工廠中管理 FSx 標籤"]



==== 調整 FSx for ONTAP檔案系統的快取容量

您可以透過工作負載工廠控制台增加和減少快取磁碟區的容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["在工作負載工廠中管理快取卷"]



=== 資料庫工作負載



==== 優化 Amazon Elastic Block Store (EBS) 資料庫節省計算器

兩個新的計算器功能改進了在使用 EBS 儲存體運行多個執行個體時的成本節約分析，以便您可以透過切換到 FSx for ONTAP來節省更多成本。

* Workload Factory 為多個資料庫主機在單一 FSx for ONTAP檔案系統上提供統一的儲存解決方案。這種整合透過減少多個資料庫主機所需的檔案系統數量來優化儲存成本，從而提高成本效益。
* Workload Factory 分析您的 EBS 效能使用情況，然後建議最佳且最具成本效益的 FSx for ONTAP配置。


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["探索已偵測到的 EBS 主機的節省方案。"]



==== 針對架構完善的儀表板，提供 Excel 報表。

您可以下載一份結構完善的儀表板的 Excel 報表。該報告提供了資料庫資源的良好架構狀態，並針對所有資源配置（包括作業系統和ONTAP 的子配置）提出了建議。



==== 適用於 Oracle 資料庫的錯誤日誌分析器

Agentic AI 驅動的錯誤日誌分析器適用於 Oracle 資料庫。此功能利用先進的機器學習演算法自動偵測和分析日誌檔案中的錯誤。該工具旨在透過根據日誌中識別的模式向開發人員提供可操作的見解和建議來簡化故障排除過程。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["了解有關 Agentic AI 驅動的錯誤日誌分析器的更多信息"]



==== 針對 Oracle 的良好架構分析

精心設計的分析包括兩種新的儲存容量配置。此分析評估並修復了現有 Oracle 資料庫部署中與交換空間分配和檔案系統餘裕相關的設定問題。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在 Workload Factory 中實作架構良好的資料庫配置"]



=== VMware 工作負載



==== 計算遷移到 Amazon Elastic VMware Service 為特定區域節省的成本

現在，您可以探索不同雲端遷移部署選項的價值，優化解決方案評估的投入，並深入了解有可能在雲端帶來價值和節省的解決方案。

您也可以查看使用 FSx for ONTAP進行 EVS 部署可以節省的 vCPU 核心數。

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["使用NetApp Workload Factory探索 Amazon Elastic VMware Service 的節省方案"]



=== 設定與管理



==== 儲存權限更新

FSx for ONTAP EMS 事件分析器使用 _operations and remediation_ 權限原則中的下列 Amazon Bedrock 權限來取得儲存工作負載的事件資料。

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["權限參考變更日誌"]



== 2025年11月2日



=== Amazon FSX for NetApp ONTAP 產品



==== 快取磁碟區管理

您可以在 Workload Factory 控制台中執行下列快取磁碟區管理操作：

* 編輯快取名稱
* 增加快取卷的容量
* 編輯快取磁碟區的掛載路徑或匯出策略
* 更改快取卷的快取方法或模式
* 預先填充快取卷
* 刪除快取卷


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["管理快取卷"]



==== 可自動進行 inode 管理

您可以啟用自動 inode 管理，而無需啟用自動容量管理。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["啟用自動 inode 管理"]



==== 容量和 inode 使用情況的閾值警告設置

容量和 inode 使用情況均有閾值警告。您可以在啟用自動容量或 inode 管理時設定這些閾值。若要使用此設置，您需要使用以下方式配置通知：link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory通知服務"^] 。



==== 容量減少可用

您可以在NetApp Workload Factory中減少 NFS 和 SMB/CIFS 磁碟區的大小。此功能可讓您減少不再需要的磁碟區的大小，從而更好地管理儲存資源。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["減少體積"]



==== 增強型 FSx for ONTAP資源狀態

Workload Factory 增強了「配置錯誤」資源狀態，使其包含對資源實際問題的解釋。



==== 精心設計的分析更新

Workload Factory 會分析您的 FSx for ONTAP檔案系統，以識別下列設定：

* 捲利用率接近滿：​​檢查是否有任何磁碟區已使用 80% 或以上的檔案容量。這有助於您確定可能需要額外產能的銷售量。
* 未經授權存取卷：檢查是否可以使用 NFS 或 SMB/CIFS 掛載路徑存取 iSCSI 卷，並允許您刪除對卷的未經授權訪問，以避免安全風險。




==== Workload Factory for Storage 的權限變更

Workload Factory 可以更清楚地說明執行特定操作所需的權限，並允許您精細地選擇所需的權限。新增憑證時，您將有三個權限選項可供選擇，而不是先前的權限模型（_唯讀_和_讀/寫_）。新的權限模型將權限策略分解如下：

* 檢視、規劃與分析：檢視 FSx for ONTAP檔案系統，了解系統運作狀況，取得系統架構完善的分析，並探索節省成本的方法。
* _操作和修復_：執行操作任務，例如調整檔案系統容量和修復檔案系統設定問題。
* 檔案系統建立和刪除：建立和刪除ONTAP檔案系統和儲存虛擬機器的 FSx。


新增憑證時，您可以根據要授予 Workload Factory 的存取級別，選擇一個或多個權限原則。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 權限參考"]



==== FSx 的ONTAP網路保險庫支持

您可以使用 FSx for ONTAP作為網路保險庫架構中的來源或目標來建立網路保險庫。網路保險庫為儲存關鍵資料提供安全隔離的環境，保護資料免受勒索軟體和其他網路威脅的侵害。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["使用 FSx 為ONTAP設定網路保險庫"]



=== 資料庫工作負載



==== 儀錶板改進

新的儀表板經過簡化和更好地組織，可以在一個屏幕上更清晰地概覽數據庫資源和工作負載工廠的關鍵功能；一張卡片突出顯示數據庫資源，一張卡片提供有關架構良好評分和分析的信息，一張卡片顯示錯誤分析，兩張卡片顯示每月成本和潛在節省，一張卡片顯示有關沙盒的信息。



==== 針對 Oracle 的良好架構分析

精心設計的分析包括對 Oracle 配置的以下評估和修復：

* 使用 NFS 協定的儲存配置作業系統：評估並修復現有 Oracle 資料庫部署的 NFS 配置問題。
* 使用 iSCSI 協定的儲存配置作業系統：評估並修復現有 Oracle 資料庫部署的 iSCSI 設定問題。
* 使用自動儲存管理 (ASM) 的儲存配置作業系統：評估現有 Oracle 資料庫部署的 ASM 設定問題。


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在 Workload Factory 中實作架構良好的資料庫配置"]



==== 資料庫工作負載工廠的權限變更

Workload Factory for Databases 更新了權限策略，以便更清楚地說明特定操作所需的權限，並允許您更精細地選擇所需的權限。新增憑證時，您將有三個權限選項可供選擇，而不是先前的權限模型（_唯讀_和_讀/寫_）。新的權限模型將權限策略分解如下：

* 檢視、規劃與分析：檢視資料庫資源清單，了解資源運作狀況，檢視資料庫配置的架構分析，取得錯誤日誌分析，並探索節省成本的方案。
* 操作與修復：對資料庫資源執行操作任務，並修復資料庫配置和底層 FSx for ONTAP檔案系統儲存的問題。
* 資料庫主機建立：根據最佳實務部署資料庫主機和底層用於ONTAP檔案系統儲存的 FSx。


新增憑證時，您可以根據要授予 Workload Factory for Databases 的存取級別，選擇一個或多個權限原則。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 權限參考"^]



==== 新增了設計精良的儀錶板介面。

資料庫選單中新增了一個名為「架構完善的儀錶板」的畫面。透過此畫面，您可以獲得整個資料庫環境配置狀態的總計視圖。



==== NetApp Backup and Recovery中資料庫部署的編輯保護

在 Workload Factory 控制台中，您可以選擇編輯受保護資源的保護，然後您將被重新導向到NetApp Console中的備份和恢復，在那裡您可以修改保護策略或計劃。

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["資料庫部署的編輯保護"]



==== 錯誤分析功能支援按標籤進行錯誤篩選

使用 Workload Factory 中的錯誤分析功能時，您可以依照基礎架構的標籤篩選並檢視 Microsoft SQL Server 錯誤日誌。這項增強功能可協助您快速對問題進行分類、檢查和解決問題。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["使用標籤篩選分析錯誤日誌"^]



=== VMware 工作負載



==== 在 FSx for ONTAP檔案系統部署精靈中引入 Amazon Elastic VMware Service 首選項

當您部署 FSx for ONTAP檔案系統以用作 Amazon Elastic VMware Service 的外部 NFS 資料儲存時，現在可以選擇資料儲存將連接到的 EVS 環境。此功能會自動填入部署精靈中的多個字段，以簡化部署過程。

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["部署建議的適用於ONTAP檔案系統的 FSx"]



==== VMware 工作負載的權限變更

VMware 工作負載能夠更清楚地說明特定操作所需的權限，並允許您精細地選擇所需的權限。新增憑證時，您將有兩個權限選項可供選擇，而不是先前的權限模型（_唯讀_和_讀/寫_）。新的權限模型將權限策略分解如下：

* 檢視、規劃與分析：檢視 EVS 虛擬化環境的清單，取得系統架構完善的分析，並探索節省成本的方法。
* 資料儲存部署與連線：將建議的 VM 佈局部署至 Amazon EVS、Amazon EC2 或 VMware Cloud on AWS vSphere 叢集，並使用自訂的Amazon FSx for NetApp ONTAP檔案系統作為外部資料儲存。


新增憑證時，您可以根據要向 VMware 工作負載提供的存取級別，選擇一個或多個權限策略。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 權限參考"^]



==== Amazon EC2 遷移顧問改進

此版本的NetApp Workload Factory for VMware 對遷移顧問體驗進行了多項改進：

* *儲存或下載遷移計劃*：您現在可以將遷移計劃儲存或下載為 PDF 或 CSV 檔案。儲存遷移計劃時，該計劃將儲存到您的 Workload Factory 帳戶中。




=== 設定與管理



==== 權限更新

在此版本中，我們對儲存、資料庫和 VMware 工作負載的權限策略進行了重大更新，以增強安全性和使用者控制。您可以更精細地自訂權限設置，根據需要新增或取消權限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 的權限參考"]



==== 儲存的新通知

NetApp Workload Factory通知服務包含儲存自動 inode 管理的通知。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory 通知"]



==== 自動容量和 inode 管理的閾值警告

可以為儲存空間設定自動容量和 inode 管理，並設定警告閾值，該閾值會觸發 Workload Factory 通知服務的通知。若要使用此功能，必須先啟用工作負載工廠通知服務。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置NetApp Workload Factory的通知"]
