= 2024-08-04
:allow-uri-read: 




== 2024-08-04

<stdin> 中未解決的指令 - 包括：： _include/Workload - fsx-Fsx-Fadoc ONTAP 。 adoc [] ：層級偏移： +1



=== Terraform 支援

您現在可以使用 Codebox 中的 Terraform 來部署檔案系統和儲存 VM 。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["建立檔案系統"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["建立儲存VM"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["使用 CodeBox 的 Terraform"^]




=== 儲存計算機中的處理量和 IOPS 建議

儲存計算機會根據 AWS 最佳實務做法、針對處理量和 IOPS 、為 ONTAP 檔案系統設定 FSX 提供建議、為您的選擇提供最佳指引。

<stdin> 中未解決的指令 - 包括：：： _include/bWorkload -setup-admin.adoc [] ：層級偏移： +1



=== Terraform 支援

Amazon FSX 支援 Terraform 、可用於 NetApp ONTAP 檔案系統部署和儲存 VM 建立。安裝與管理指南現在提供如何從 Codebox 使用 Terraform 的說明。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["使用 CodeBox 的 Terraform"^]



== 2024-07-07

<stdin> 中未解決的指令 - 包括：： _include/Workload - fsx-Fsx-Fadoc ONTAP 。 adoc [] ：層級偏移： +1



=== 適用於 Amazon FSX for NetApp ONTAP 的工作負載工廠初始版本

Amazon FSX for NetApp ONTAP 現在已正式推出 Workload Factory 。

<stdin> 中未解決的指令 - 包括：：： _include/bWorkload -setup-admin.adoc [] ：層級偏移： +1



=== Workload Factory 的初始版本

BlueXP Workload Factory for AWS 是功能強大的生命週期管理平台、可協助您使用 Amazon FSX for NetApp ONTAP 檔案系統來最佳化工作負載。使用 Workload Factory 和適用於 ONTAP 的 FSX 可簡化的工作負載包括資料庫、 VMware 在 AWS 上移轉至 VMware Cloud 、 AI 聊天機器人程式等。
