---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 瞭解 BlueXP  工作負載工廠工作負載的最新變更。 
---
= BlueXP  工作負載工廠最近的變更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
瞭解 BlueXP  工作負載工廠工作負載的最新變更。



== 2025-06-29



=== VMware 工作負載



==== 引入對 Amazon Elastic VMWare Service 的遷移顧問支持

BlueXP VMware 工作負載工廠現已支援 Amazon Elastic VMware Service。您可以使用遷移顧問快速將本機 VMware 工作負載移轉到 Amazon Elastic VMware Service，從而優化成本並更好地控制您的 VMware 環境，而無需重構或重新建置應用程式平台。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["使用遷移顧問為 Amazon EVS 建立部署計劃"]



=== GenAI 工作負載



==== 支援通用 NFS/SMB 檔案系統上託管的資料來源

現在您可以從通用 SMB 或 NFS 共用中新增資料來源。這使您能夠包含儲存在 Amazon FSx for NetApp ONTAP 以外的檔案系統所託管的磁碟區上的檔案。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["在知識庫中新增資料來源"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["新增資料來源"]



=== 設定與管理



==== BlueXP 工作負載工廠通知服務支持

BlueXP 工作負載工廠通知服務支援工作負載工廠向 BlueXP 警報服務或 Amazon SNS 主題發送通知。發送到 BlueXP 警報的通知會顯示在 BlueXP 警報面板中。當工作負載工廠向 Amazon SNS 主題發布通知時，該主題的訂閱者（例如人員或其他應用程式）會在為該主題配置的終端節點上收到通知（例如電子郵件或簡訊）。

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作負載工廠通知"]



== 2025-06-16



=== 建構者的工作量



==== 克隆支持

現在您可以在 BlueXP 工作負載工廠中為 Builders 複製專案。複製項目時，Builders 會根據快照建立一個新項目，其配置與原始項目相同。克隆功能對於快速建立類似項目或進行測試非常有用。您可以按照 Builders 中的說明安裝新的項目克隆。

https://docs.netapp.com/us-en/workload-builders/version-projects.html["管理 Builders 專案的 BlueXP 工作負載工廠版本"]



== 2025-06-08



=== Amazon FSX for NetApp ONTAP 產品



==== 全新精心設計的分析和問題修復支持

FSx for ONTAP 檔案系統的自動容量管理現在作為配置分析包含在精心設計的狀態儀表板中。

此外，工作負載工廠現在支援修復以下配置問題：

* SSD 容量臨界值
* 資料分層
* 排程的本機快照
* FSx for ONTAP 備份
* 遠端資料複寫
* 儲存效率
* 自動容量管理


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["修復配置問題"]



== 2025-06-03



=== Amazon FSX for NetApp ONTAP 產品



==== 磁碟區自動增長增強

現在，您可以設定磁碟區的自動成長大小，以便磁碟區大小可以超出業務需求和應用程式要求的預先配置大小。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["啟用Volume自動擴充"]



==== 架構完善的分析更新

工作負載工廠現在會分析您的 FSx for ONTAP 檔案系統，以檢查是否正在利用儲存效率，包括資料壓縮、壓縮和重複資料刪除。儲存效率衡量檔案系統利用可用空間的效率。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["查看儲存效率的良好架構狀態"]



==== 儲存儀表板增強功能

從今天開始，當您從工作負載工廠控制台開啟儲存工作負載時，您將看到「儀表板」。全新設計的儀表板提供 FSx for ONTAP 系統的整體視圖，包括檔案系統數量、SSD 總容量、架構完善的狀態概覽、資料保護概覽以及複製關係的運作狀況。



==== 磁碟區選項卡增強功能

儲存工作負載對工作負載工廠控制台中 FSx for ONTAP 檔案系統內的「磁碟區」標籤進行了增強。增強功能包括：

* *新卡*：SSD 容量、容量池和自主勒索軟體防護 (ARP)
* *新列*：容量分佈、已使用 SSD 容量、已使用容量池和 SSD 效率




==== 磁碟區所建立的儲存效率更新

建立新磁碟區時，預設啟用儲存效率，包括資料壓縮、壓縮和重複資料刪除。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["在工作負載工廠中建立新卷"]



=== 資料庫工作負載



==== PostgreSQL 和 Oracle 檢測

現在，您可以在工作負載工廠控制台中發現 AWS 帳戶中執行 PostgreSQL 伺服器資料庫和 Oracle 資料庫部署的執行個體。已發現的實例將顯示在資料庫清單中。



==== 更新了「優化」術語

工作負載工廠以前稱為“最佳化”，現在使用“良好架構的問題”和“良好架構的狀態”來描述資料庫配置的分析，並使用“修復”來描述改善資料庫配置以滿足最佳實踐建議的機會的補救措施。

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["工作負載工廠中的資料庫環境配置分析"]



==== 改進了主機實例的入職培訓

工作負載工廠現在使用「註冊」來表示主機執行個體的註冊，而不是像以前那樣使用「未偵測到」、「未託管」或「託管」等術語。新的註冊流程包括對主機執行個體進行驗證和準備，以便您可以在工作負載工廠控制台中建立、監控、分析和修復資料庫配置中的資源。註冊流程中的準備步驟指示您的主機執行個體是否已準備好進行管理。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["執行個體管理"]



=== GenAI 工作負載



==== Tracker 可用於監控及追蹤作業

GenAI 現已提供 Tracker 監控功能。您可以使用 Tracker 監控和追蹤待處理、正在進行和已完成操作的進度和狀態，查看操作任務和子任務的詳細信息，診斷任何問題或故障，編輯失敗操作的參數，以及重試失敗的操作。

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["使用 BlueXP 工作負載工廠中的 Tracker 監控工作負載操作"]



==== 為知識庫選擇重新排序模型

現在，您可以透過選擇與知識庫配合使用的特定重排序模型來提高重排序查詢結果的相關性。 GenAI支援 Cohere Rerank 和 Amazon Rerank 模型。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["建立 GenAI 知識庫"]



== 2025-05-04



=== Amazon FSX for NetApp ONTAP 產品



==== 適用於 ONTAP 檔案系統的 FSX 的自主勒索軟體保護

使用自動勒索軟體保護（ ARP ）來保護您的資料，這項功能會在 NAS （ NFS/SMB ）環境中使用工作負載分析來偵測並警告可能是勒索軟體攻擊的異常活動。當懷疑有攻擊時， ARP 也會建立新的不可變快照，您可以從中還原資料。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["運用自主勒索軟體保護來保護資料"]



==== FlexGroup Volume 重新平衡增強功能

BlueXP  工作負載工廠推出 FlexGroup Volume 重新平衡精靈，其中有數個配置選項可重新平衡 FlexGroup Volume 中的資料。重新平衡會將資料平均地重新分配給 FlexGroup 成員磁碟區。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["重新平衡 FlexGroup 磁碟區中的容量"]



==== 為 ONTAP 檔案系統實作 FSX 的最佳實務做法

BlueXP  工作負載工廠提供儀表板，讓您檢視檔案系統組態架構良好的狀態。您可以利用此分析，為 ONTAP 檔案系統的 FSX 實作最佳實務做法。檔案系統組態分析包括下列組態： SSD 容量臨界值，排程本機快照， ONTAP 備份排程的 FSX ，資料分層和遠端資料複寫。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["瞭解檔案系統組態的架構良好分析"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["為您的檔案系統實作最佳實務做法"]




==== 雙傳輸協定 Volume 安全樣式選項

您可以選擇 NTFS 或 UNIX 作為磁碟區的安全樣式，以決定使用者和權限存取磁碟區的方法。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["建立Volume"]



==== 複寫增強功能



===== 支援從適用於 ONTAP 的 FSX 到內部部署的反向複寫

從適用於 ONTAP 檔案系統的 FSX 到內部部署 ONTAP 叢集，現在可從工作負載原廠主控台進行反向複寫。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["反轉複寫"]



===== 資料保護 Volume 複寫

您現在可以複寫資料保護磁碟區。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["複寫資料保護磁碟區"]



===== 多個 Volume 選擇

您可以選擇多個磁碟區，以便精確選取要複寫的磁碟區。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["建立複寫關係"]



===== 長期保留原則標籤

當您為複寫關係啟用長期保留時，來源和目標 Volume 標籤必須完全相符。現在， BlueXP  工作負載工廠可以自動為您建立遺失的來源 Volume 標籤。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["建立複寫關係"]



==== 可在 Volume 建立中看到 ONTAP 檔案名稱的 FSX

我們已改善在磁碟區建立期間， ONTAP 檔案系統的 FSX 可見度。建立磁碟區時，您會看到適用於 ONTAP 檔案系統的 FSX ，因此您可以確切知道磁碟區的建立位置。



==== 整個儲存工作負載均可見 AWS 帳戶

我們改善了儲存工作負載的帳戶可見度。當您瀏覽至 * Volumes * ， * Storage VMS* 和 * Replication * 標籤時，您會看到 AWS 帳戶。



==== 連結關聯增強功能

* 您可以在「庫存」索引標籤中，快速建立從適用於 ONTAP 檔案系統的 FSX 連結的關聯。
* BlueXP  工作負載工廠現在支援使用替代的 ONTAP 使用者認證進行連結關聯。




==== AWS Secrets Manager 的連結驗證支援

您現在可以選擇使用 AWS Secrets Manager 的機密來驗證連結，這樣就不需要使用儲存在 BlueXP  工作負載工廠中的認證資料。



==== Tracker 回應支援

Tracker 現在提供 API 回應，讓您可以查看與工作相關的 REST API 輸出。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["使用 Tracker 監控作業"]



==== 從備份還原磁碟區時進行容量驗證

從備份還原磁碟區時， BlueXP  工作負載工廠會判斷您是否有足夠的容量進行還原，如果沒有，也可以自動新增 SSD 儲存層容量。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["從備份還原磁碟區"]



==== 支援替代的 ONTAP 使用者認證

工作負載工廠現在支援替代的 ONTAP 認證集，可用來建立檔案系統，將安全風險降至最低。您可以選擇不同的 ONTAP 認證集，或選擇不為 fsxadmin 和 vsaadmin 使用者提供密碼，而不只使用 fsxadmin 使用者。



==== 更新的權限術語

工作負載工廠使用者介面和文件現在使用“只讀”來指讀取權限，使用“讀取/寫入”來指稱自動化權限。



=== 資料庫工作負載



==== 儀表板增強功能

* 當您在 BlueXP  工作負載工廠主控台的索引標籤之間瀏覽時，可以使用跨帳戶和跨區域檢視。新的檢視可改善資源管理，監控及最佳化。
* 從儀表板的 * 潛在節約 * 方塊中，您可以從 Amazon Elastic Block Store 或 Amazon FSX for Windows 檔案伺服器切換至適用於 ONTAP 的 FSX ，快速檢閱可能節省的成本。




==== 可用於資料庫組態的臨機操作掃描

資料庫的 BlueXP  工作負載原廠會自動掃描採用 FSX 的託管 Microsoft SQL Server 執行個體 ONTAP ，以找出可能的組態問題。除了每日掃描之外，您還可以隨時進行掃描。



==== 刪除內部部署評估記錄

探索 Microsoft SQL Server 內部部署主機的節約效益之後，您可以選擇從 BlueXP  工作負載工廠移除內部部署主機記錄。



==== 最佳化增強功能



===== 實體複本清理

複本清理評估與補救可識別及管理昂貴的舊複本。60 天以上的複本可從 BlueXP  工作負載原廠主控台重新整理或刪除。



===== 延遲和關閉組態分析

某些組態可能不適用於您的資料庫環境。您現在可以選擇將特定組態分析延遲 30 天，或是關閉分析。



==== 刪除內部部署評估記錄

探索 Microsoft SQL Server 內部部署主機的節約效益之後，您可以選擇從 BlueXP  工作負載工廠移除內部部署主機記錄。



==== 更新的權限術語

工作負載工廠使用者介面和文件現在使用“只讀”來指讀取權限，使用“讀取/寫入”來指稱自動化權限。



=== VMware 工作負載



==== Amazon EC2 移轉顧問的改善

此版本的 BlueXP  工作負載工廠適用於 VMware ，可改善 Amazon EC2 移轉顧問體驗：

* NetApp 資料基礎架構洞見資料來源 * ：工作負載工廠現在直接與 NetApp 資料基礎架構洞見連結，以便在使用 EC2 移轉顧問資料收集器時收集 VMware 部署資訊。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用移轉顧問為 Amazon EC2 建立部署計畫"]



==== 更新的權限術語

工作負載工廠使用者介面和文件現在使用“只讀”來指讀取權限，使用“讀取/寫入”來指稱自動化權限。



=== GenAI 工作負載



==== 支援 NetApp Connector for Amazon Q Business

此版本的 GenAI 引入了對 NetApp Connector for Amazon Q Business 的支持，使您能夠為 Amazon Q Business 建立連接器。與為 Amazon Bedrock 建立 GenAI 知識庫相比，較少的初始組態，可快速輕鬆地利用 Amazon Q Business AI 助理。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["為 Amazon Q Business 建立 NetApp 連接器"]



==== 增強的聊天模式支援

GenAI 現在支援下列額外的聊天模式以供知識庫使用：

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AI 機型"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titan 文字模型"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["中繼 Llama 機型"^]
* link:https://docs.ai21.com/["Jamba 1.5 機型"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohere Command 模型"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Deepseek 機型"^]


GenAI 支援 Amazon Bedrock 支援的每個供應商機型：link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon 基礎架構支援的基礎模型"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["建立 GenAI 知識庫"]



==== 更新的權限術語

工作負載工廠使用者介面和文件現在使用“只讀”來指讀取權限，使用“讀取/寫入”來指稱自動化權限。



=== 設定與管理



==== CloudShell 自動完整支援

使用 BlueXP  工作負載原廠 CloudShell 時，您可以開始輸入命令，然後按 Tab 鍵檢視可用選項。如果存在多種可能性， CLI 會顯示建議清單。此功能可將錯誤降至最低，並加速命令執行，進而提升生產力。



==== 更新的權限術語

工作負載工廠使用者介面和文件現在使用“只讀”來指讀取權限，使用“讀取/寫入”來指稱自動化權限。



=== 建構者的工作量



==== 更新的權限術語

工作負載工廠使用者介面和文件現在使用“只讀”來指讀取權限，使用“讀取/寫入”來指稱自動化權限。



== 2025-04-04



=== 資料庫工作負載



==== 最佳化增強功能

最佳化資料庫環境時，可以使用新的最佳化評估，修正及顯示多個資源。



===== 恢復能力評估

這些增強功能包括新的恢復能力評估，以檢查資料庫環境是否已設定資料備援和災難恢復功能。

* 適用於 ONTAP 備份的 FSX ：分析服務 SQL Server 執行個體磁碟區之 ONTAP 檔案系統的 FSX 是否已設定 ONTAP 備份的排程 FSX 。
* 跨區域複寫：評估服務 Microsoft SQL Server 執行個體的 ONTAP 檔案系統的 FSX 是否設定為跨區域複寫。




===== 運算修正

「接收端調整」（ RSS ）補救功能可將 RSS 設定為在多個處理器之間分散網路處理，並確保有效的負載分配。



===== 本機快照修正

本機快照修正可為 Microsoft SQL Server 執行個體設定磁碟區的快照原則，以在資料遺失時保持資料庫環境的恢復能力。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["最佳化組態"]



===== 支援多種資源選擇

最佳化資料庫組態時，您現在可以選擇特定資源，而非所有資源。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["最佳化組態"]



==== 改善的庫存檢視

工作負載原廠主控台中的「庫存」索引標籤已簡化，因此只包含執行於 Amazon FSX for NetApp ONTAP 上的 SQL Server 。現在您可以在內部部署中找到 SQL Server ，並在 Amazon Elastic Block Store 和 Amazon FSX for Windows File Server 的 Explore 節約標籤中執行。



==== 可用於 PostgreSQL 伺服器部署的快速建立

您可以使用此快速部署選項，建立具有 HA 組態和內嵌最佳實務做法的 PostgreSQL 伺服器。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["在 BlueXP  工作負載工廠中建立 PostgreSQL 伺服器"]



== 20205-03-30



=== VMware 工作負載



==== Amazon EC2 移轉顧問的改善

此版本的 BlueXP  工作負載工廠適用於 VMware ，對 Amazon EC2 移轉顧問體驗有幾項改善：

* * 增強型 Volume 指派指南 * ： EC2 移轉顧問「分類」和「封裝」步驟中的 Volume 指派資訊，具有增強的易讀性和可用性。系統會顯示每個 Volume 的更多實用資訊，讓您能夠更有效地識別磁碟區，並判斷如何指派磁碟區。
* * 資料收集器指令碼效率提升 * ： EC2 移轉顧問資料收集器指令碼可在收集資料以進行較小的 VM 部署時，最佳化 CPU 使用率。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用移轉顧問為 Amazon EC2 建立部署計畫"]



=== 設定與管理



==== CloudShell 會針對 ONTAP CLI 命令回報 AI 產生的錯誤回應

使用 CloudShell 時，每次您發出 ONTAP CLI 命令並發生錯誤時，您都可以取得 AI 產生的錯誤回應，包括故障說明，故障原因及詳細解決方法。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用 CloudShell"]



==== IAM ： SimulatePermissionPolicy 權限更新

現在您可以在工作負載原廠主控台管理 `iam:SimulatePrincipalPolicy`權限，只要新增額外的 AWS 帳戶認證，或新增 GenAI 工作負載等新工作負載功能即可。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["權限參考變更記錄"]



== 2024-12-01



=== 建構者的工作量



==== 建置者工作負載初始版本

適用於 Builders 的 BlueXP  工作負載工廠可簡化軟體版本的使用與存取，免除自訂工具或指令碼的需求。它可讓您將軟體版本當作即時複本使用，並與 Perforce Helix Core 整合，作為開發程序的便利工作區，節省時間與資源。

初始版本包含管理專案和工作區的功能，以及使用 CodeBox 自動化行動。您也可以將 Builders 與 Perforce Helix Core 整合，以便管理每個專案的不同版本，並在它們之間快速切換。
