= 最佳化增強功能
:allow-uri-read: 




=== 最佳化增強功能

最佳化資料庫環境時，可以使用新的最佳化評估，修正及顯示多個資源。



==== 恢復能力評估

這些增強功能包括新的恢復能力評估，以檢查資料庫環境是否已設定資料備援和災難恢復功能。

* 適用於 ONTAP 備份的 FSX ：分析服務 SQL Server 執行個體磁碟區之 ONTAP 檔案系統的 FSX 是否已設定 ONTAP 備份的排程 FSX 。
* 跨區域複寫：評估服務 Microsoft SQL Server 執行個體的 ONTAP 檔案系統的 FSX 是否設定為跨區域複寫。




==== 運算修正

「接收端調整」（ RSS ）補救功能可將 RSS 設定為在多個處理器之間分散網路處理，並確保有效的負載分配。



==== 本機快照修正

本機快照修正可為 Microsoft SQL Server 執行個體設定磁碟區的快照原則，以在資料遺失時保持資料庫環境的恢復能力。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["最佳化組態"]



==== 支援多種資源選擇

最佳化資料庫組態時，您現在可以選擇特定資源，而非所有資源。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["最佳化組態"]



=== 改善的庫存檢視

工作負載原廠主控台中的「庫存」索引標籤已簡化，因此只包含執行於 Amazon FSX for NetApp ONTAP 上的 SQL Server 。現在您可以在內部部署中找到 SQL Server ，並在 Amazon Elastic Block Store 和 Amazon FSX for Windows File Server 的 Explore 節約標籤中執行。



=== 可用於 PostgreSQL 伺服器部署的快速建立

您可以使用此快速部署選項，建立具有 HA 組態和內嵌最佳實務做法的 PostgreSQL 伺服器。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["在 BlueXP  工作負載工廠中建立 PostgreSQL 伺服器"]
