= BlueXP 工作負載工廠通知服務支持
:allow-uri-read: 




=== BlueXP 工作負載工廠通知服務支持

BlueXP 工作負載工廠通知服務支援工作負載工廠向 BlueXP 警報服務或 Amazon SNS 主題發送通知。發送到 BlueXP 警報的通知會顯示在 BlueXP 警報面板中。當工作負載工廠向 Amazon SNS 主題發布通知時，該主題的訂閱者（例如人員或其他應用程式）會在為該主題配置的終端節點上收到通知（例如電子郵件或簡訊）。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作負載工廠通知"^]

工作負載工廠為資料庫提供以下通知：

* 結構完善的報告
* 主機部署
* 保護




=== 用於註冊實例的入門增強功能

資料庫工作負載工廠改進了在 Amazon FSx for NetApp ONTAP 儲存上執行的執行個體的註冊流程。現在，您可以批次選擇實例進行註冊。執行個體註冊完成後，您可以在工作負載工廠控制台中建立和管理資料庫主機資源。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["執行個體管理"]



=== Microsoft Multipath I/O 逾時設定的分析與修復

資料庫主機執行個體的架構完善狀態現在包含對 Microsoft 多路徑 I/O (MPIO) 逾時設定的分析和修復。將 MPIO 逾時設定為 60 秒可確保 FSx for ONTAP 儲存故障轉移期間的連線性和穩定性。如果 MPIO 設定未正確設置，工作負載工廠將提供修復程序，將 MPIO 逾時值設定為 60 秒。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在工作負載工廠中實現架構良好的資料庫配置"]



=== 主機庫存中的圖形增強功能

在主機清單畫面中，各種資源利用率圖表（例如吞吐量和 IOPS）現在顯示 7 天的數據，以便您可以更有效率地從工作負載工廠控制台監控 SQL 節點的效能。從 SQL 節點收集的效能指標將保存在 Amazon CloudWatch 中，可用於 Logs Insights 或與您環境中的其他分析服務整合。

從主機清單中的實例和資料庫標籤中，我們增強了主機保護的描述和視覺化。



=== 工作負載工廠中對 Windows 身份驗證的支持

現在，工作負載工廠支援使用 Windows 驗證使用者的 SQL Server 驗證來註冊主機執行個體並受益於主機管理功能。

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["在資料庫的工作負載工廠中註冊主機實例"]
