= Agentic AI 驅動的錯誤日誌分析器
:allow-uri-read: 




=== Agentic AI 驅動的錯誤日誌分析器

Agentic AI 驅動的錯誤日誌分析器是一項新功能，它利用先進的機器學習演算法自動偵測和分析日誌檔案中的錯誤。該工具旨在透過根據日誌中識別的模式向開發人員提供可操作的見解和建議來簡化故障排除過程。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["了解有關 Agentic AI 驅動的錯誤日誌分析器的更多信息"]



=== Oracle 支援

工作負載工廠包括對 Oracle 資料庫的支援。在工作負載工廠控制台中，您可以從庫存中查看 Oracle 資料庫，註冊資料庫以使用工作負載工廠中的進階功能，並使用架構良好的功能分析 Oracle 資料庫以符合最佳實務。良好的架構分析決定了 Oracle 資料庫的儲存配置是否已最佳化。您可以使用此資訊對資料庫部署做出明智的決策並確保它們有效運作。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在工作負載工廠中實現架構良好的資料庫配置"]



=== 支援在第二代 FSx for ONTAP檔案系統上部署 Microsoft SQL Server

工作負載工廠支援在第二代 FSx for ONTAP檔案系統上部署 Microsoft SQL Server。此增強功能可讓您在管理 SQL Server 工作負載的同時利用第二代檔案系統中的最新功能和效能改進。



=== 用於 SQL Server 保護的 Windows 驗證

使用 Windows 憑證對 Microsoft SQL Server 執行個體進行驗證已嵌入到工作流程中，以準備使用BlueXP backup and recovery原來保護 Microsoft SQL Server 主機。這曾經是需要手動完成的先決步驟。相反，如果您尚未使用 Windows 憑證在工作負載工廠中註冊主機，系統將提示您與管理員存取權限共用 Windows 憑證。

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["了解如何透過工作負載工廠控制台保護 Microsoft SQL Server 工作負載"] 。



=== 架構良好的分析包括 SQL Server 的 MTU 對齊

精心設計的分析評估並修復了 FSx for ONTAP儲存上 Microsoft SQL Server 跨端點的最大傳輸單元 (MTU) 錯位。調整 MTU 設定有助於最佳化網路效能並減少 SQL Server 工作負載的延遲。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在工作負載工廠中實現架構良好的資料庫配置"]
