= 一次性評估
:allow-uri-read: 




=== 一次性評估

Workload Factory 現在提供一次性評估服務，隨時分析您的資料庫部署配置—無論是新部署、遷移後部署、故障排除等等。您將獲得最佳化部署配置並遵循最佳實務的建議。這是您無需完全投入設定流程即可使用這項架構完善的功能的絕佳機會。您無需在 Workload Factory 中儲存憑證、註冊資料庫資源或設定外部連線即可評估您的資料庫。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["對您的資料庫部署進行一次性評估"]



=== 支援在 Microsoft SQL Server 上註冊 Always On 可用性群組，以及在 Oracle 上註冊 Data Guard

現在，您可以在 NetApp Workload Factory 的資料庫工作負載中發現並註冊採用 Always On 可用性群組（AOAG）部署模型的 Microsoft SQL Server 執行個體以及採用 Data Guard 部署模型的 Oracle 資料庫。此增強功能可讓您在 Workload Factory 主控台中更好地管理 SQL Server 和 Oracle 資源。

註冊 AOAG 執行個體和 Data Guard 資料庫後、您可以利用 Workload Factory for Databases 中的各種功能、例如檢視資源詳細資料和分析錯誤記錄。

Workload Factory for Databases 也支援採用 AOAG 部署模型的 Microsoft SQL Server 執行個體進行架構完善的分析。您可以分析可用性群組中 SQL Server 執行個體的組態，並獲得最佳化部署組態和遵循最佳實務做法的建議。註冊您的 AOAG 執行個體即可啟用此功能。

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html#register-a-sql-server-instance["在 Workload Factory for Databases 註冊資源"]



=== 針對 Oracle 的良好架構分析

精心設計的分析包括 Oracle 的 *Operating system patches* ，用於檢查您的作業系統是否安裝了最新的修補程式，並告訴您如何安裝。

此外，針對 Oracle 精心設計的分析功能會在儲存佈局等組態與其他組態有相依性時發出通知。該通知會告知您需要採取哪些行動來最佳化連結的組態，以便我們提供的所有建議都是最佳的。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["在 Workload Factory 中實作架構良好的資料庫配置"]



=== Oracle 內部部署資料庫環境成本分析與遷移規劃

Workload Factory for Databases 現在可以分析並協助您規劃將 Oracle 內部部署資料庫移轉至 Amazon FSx for NetApp ONTAP。您可以使用節省成本計算機來估算在雲端中執行 Oracle 內部部署資料庫環境的成本，並檢閱將內部部署資料庫環境移轉至雲端的建議。

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["探索內部部署資料庫環境的節省方案"]



=== Workload Factory 中新增了「問我」書籤

我們在 Workload Factory 控制台的每個畫面上都新增了 Ask Me 書籤。這項改進讓您在需要協助時更輕鬆快速地存取 Ask Me。Ask Me 是我們的 AI 助手，您可以詢問有關自身工作負載環境的問題，直接從您的環境中獲取個人化見解，並查看先前的對話記錄。

您可以點擊新增的書籤，從任何頁面開啟 Ask Me。它會在側邊面板中啟動 Ask Me，不會中斷您目前的工作，並提供與您目前操作相關的快速說明和建議。

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["深入瞭解 Ask Me"^]
